### ISSUE TITLE
It does not work at all !?

### ISSUE THREAD

**Issue by Ahmettassak** [micheljung/downlords-faf-client#205]
Today I found out about this and installed it. To my surpize it does not even login at all.

Any solutions so that I can at least give some feedback?

**Comment by micheljung** [comment]
Hi,

I think the problem has been solved, but not yet released. I'll release the
fixed version ASAP, but I'm not near my computer atm :)

**Comment by micheljung** [comment]
Duplicate of #203

**Comment by micheljung** [comment]
Please try the fixed version: https://github.com/micheljung/downlords-faf-client/releases/tag/v0.6.7-alpha

**Comment by Androish** [comment]
Any news on the memory leak btw? still an issue? (sorry for hijacking :) )

**Comment by micheljung** [comment]
1-2 leaks have been solved, but there's still something remaining. I have a memory dump lying around which I didn't have time yet to inspect :-)

**Comment by Androish** [comment]
I guess I should test and see how long I can run the new version then if it is 4h+ I can use it as my main client :)

**Comment by micheljung** [comment]
I wouldn't yet, it was reported that it loses connection to players during a game. No idea yet if this is a client bug.
Feel free to use it but be prepared for such things as long as it's ALPHA ;)
